install_name_tool -change /usr/local/opt/qscintilla2/lib/libqscintilla2.11.dylib @rpath/Deps/libqscintilla2.11.dylib ./libqscintilla2.11.3.0.dylib
install_name_tool -change /usr/local/opt/qt/lib/QtGui.framework/Versions/4/QtGui @rpath/Deps/QtGui ./libqscintilla2.11.3.0.dylib
install_name_tool -change /usr/local/opt/qt/lib/QtCore.framework/Versions/4/QtCore @rpath/Deps/QtCore ./libqscintilla2.11.3.0.dylib
install_name_tool -change /usr/lib/libc++.1.dylib @rpath/Deps/libc++.1.dylib ./libqscintilla2.11.3.0.dylib
install_name_tool -change /usr/lib/libSystem.B.dylib @rpath/Deps/libSystem.B.dylib ./libqscintilla2.11.3.0.dylib
install_name_tool -change /usr/local/opt/qscintilla2/lib/libqscintilla2.11.dylib @rpath/Deps/libqscintilla2.11.dylib ./libqscintilla2.11.3.dylib
install_name_tool -change /usr/local/opt/qt/lib/QtGui.framework/Versions/4/QtGui @rpath/Deps/QtGui ./libqscintilla2.11.3.dylib
install_name_tool -change /usr/local/opt/qt/lib/QtCore.framework/Versions/4/QtCore @rpath/Deps/QtCore ./libqscintilla2.11.3.dylib
install_name_tool -change /usr/lib/libc++.1.dylib @rpath/Deps/libc++.1.dylib ./libqscintilla2.11.3.dylib
install_name_tool -change /usr/lib/libSystem.B.dylib @rpath/Deps/libSystem.B.dylib ./libqscintilla2.11.3.dylib
install_name_tool -change /usr/local/opt/qscintilla2/lib/libqscintilla2.11.dylib @rpath/Deps/libqscintilla2.11.dylib ./libqscintilla2.11.dylib
install_name_tool -change /usr/local/opt/qt/lib/QtGui.framework/Versions/4/QtGui @rpath/Deps/QtGui ./libqscintilla2.11.dylib
install_name_tool -change /usr/local/opt/qt/lib/QtCore.framework/Versions/4/QtCore @rpath/Deps/QtCore ./libqscintilla2.11.dylib
install_name_tool -change /usr/lib/libc++.1.dylib @rpath/Deps/libc++.1.dylib ./libqscintilla2.11.dylib
install_name_tool -change /usr/lib/libSystem.B.dylib @rpath/Deps/libSystem.B.dylib ./libqscintilla2.11.dylib
install_name_tool -change /usr/local/opt/qscintilla2/lib/libqscintilla2.11.dylib @rpath/Deps/libqscintilla2.11.dylib ./libqscintilla2.dylib
install_name_tool -change /usr/local/opt/qt/lib/QtGui.framework/Versions/4/QtGui @rpath/Deps/QtGui ./libqscintilla2.dylib
install_name_tool -change /usr/local/opt/qt/lib/QtCore.framework/Versions/4/QtCore @rpath/Deps/QtCore ./libqscintilla2.dylib
install_name_tool -change /usr/lib/libc++.1.dylib @rpath/Deps/libc++.1.dylib ./libqscintilla2.dylib
install_name_tool -change /usr/lib/libSystem.B.dylib @rpath/Deps/libSystem.B.dylib ./libqscintilla2.dylib
install_name_tool -change /usr/local/opt/qscintilla2/lib/libqscintilla2.11.dylib @rpath/Deps/libqscintilla2.11.dylib ./libqscintilla2.11.3.0.dylib
install_name_tool -change /usr/local/opt/qt/lib/QtGui.framework/Versions/4/QtGui @rpath/Deps/QtGui ./libqscintilla2.11.3.0.dylib
install_name_tool -change /usr/local/opt/qt/lib/QtCore.framework/Versions/4/QtCore @rpath/Deps/QtCore ./libqscintilla2.11.3.0.dylib
install_name_tool -change /usr/lib/libc++.1.dylib @rpath/Deps/libc++.1.dylib ./libqscintilla2.11.3.0.dylib
install_name_tool -change /usr/lib/libSystem.B.dylib @rpath/Deps/libSystem.B.dylib ./libqscintilla2.11.3.0.dylib
install_name_tool -change /usr/local/opt/qscintilla2/lib/libqscintilla2.11.dylib @rpath/Deps/libqscintilla2.11.dylib ./libqscintilla2.11.3.dylib
install_name_tool -change /usr/local/opt/qt/lib/QtGui.framework/Versions/4/QtGui @rpath/Deps/QtGui ./libqscintilla2.11.3.dylib
install_name_tool -change /usr/local/opt/qt/lib/QtCore.framework/Versions/4/QtCore @rpath/Deps/QtCore ./libqscintilla2.11.3.dylib
install_name_tool -change /usr/lib/libc++.1.dylib @rpath/Deps/libc++.1.dylib ./libqscintilla2.11.3.dylib
install_name_tool -change /usr/lib/libSystem.B.dylib @rpath/Deps/libSystem.B.dylib ./libqscintilla2.11.3.dylib
install_name_tool -change /usr/local/opt/qscintilla2/lib/libqscintilla2.11.dylib @rpath/Deps/libqscintilla2.11.dylib ./libqscintilla2.11.dylib
install_name_tool -change /usr/local/opt/qt/lib/QtGui.framework/Versions/4/QtGui @rpath/Deps/QtGui ./libqscintilla2.11.dylib
install_name_tool -change /usr/local/opt/qt/lib/QtCore.framework/Versions/4/QtCore @rpath/Deps/QtCore ./libqscintilla2.11.dylib
install_name_tool -change /usr/lib/libc++.1.dylib @rpath/Deps/libc++.1.dylib ./libqscintilla2.11.dylib
install_name_tool -change /usr/lib/libSystem.B.dylib @rpath/Deps/libSystem.B.dylib ./libqscintilla2.11.dylib
install_name_tool -change /usr/local/opt/qscintilla2/lib/libqscintilla2.11.dylib @rpath/Deps/libqscintilla2.11.dylib ./libqscintilla2.dylib
install_name_tool -change /usr/local/opt/qt/lib/QtGui.framework/Versions/4/QtGui @rpath/Deps/QtGui ./libqscintilla2.dylib
install_name_tool -change /usr/local/opt/qt/lib/QtCore.framework/Versions/4/QtCore @rpath/Deps/QtCore ./libqscintilla2.dylib
install_name_tool -change /usr/lib/libc++.1.dylib @rpath/Deps/libc++.1.dylib ./libqscintilla2.dylib
install_name_tool -change /usr/lib/libSystem.B.dylib @rpath/Deps/libSystem.B.dylib ./libqscintilla2.dylib
