install_name_tool -change /usr/local/opt/qt/lib/phonon.framework/Versions/4/phonon @rpath/Deps/phonon ./PyQt4/phonon.so
install_name_tool -change /usr/local/opt/qt/lib/QtGui.framework/Versions/4/QtGui @rpath/Deps/QtGui ./PyQt4/phonon.so
install_name_tool -change /usr/local/opt/qt/lib/QtCore.framework/Versions/4/QtCore @rpath/Deps/QtCore ./PyQt4/phonon.so
install_name_tool -change /usr/lib/libc++.1.dylib @rpath/Deps/libc++.1.dylib ./PyQt4/phonon.so
install_name_tool -change /usr/lib/libSystem.B.dylib @rpath/Deps/libSystem.B.dylib ./PyQt4/phonon.so
install_name_tool -change /usr/lib/libc++.1.dylib @rpath/Deps/libc++.1.dylib ./PyQt4/Qt.so
install_name_tool -change /usr/lib/libSystem.B.dylib @rpath/Deps/libSystem.B.dylib ./PyQt4/Qt.so
install_name_tool -change /usr/local/opt/qt/lib/QtCore.framework/Versions/4/QtCore @rpath/Deps/QtCore ./PyQt4/QtCore.so
install_name_tool -change /usr/lib/libc++.1.dylib @rpath/Deps/libc++.1.dylib ./PyQt4/QtCore.so
install_name_tool -change /usr/lib/libSystem.B.dylib @rpath/Deps/libSystem.B.dylib ./PyQt4/QtCore.so
install_name_tool -change /usr/local/opt/qt/lib/QtDeclarative.framework/Versions/4/QtDeclarative @rpath/Deps/QtDeclarative ./PyQt4/QtDeclarative.so
install_name_tool -change /usr/local/opt/qt/lib/QtScript.framework/Versions/4/QtScript @rpath/Deps/QtScript ./PyQt4/QtDeclarative.so
install_name_tool -change /usr/local/opt/qt/lib/QtCore.framework/Versions/4/QtCore @rpath/Deps/QtCore ./PyQt4/QtDeclarative.so
install_name_tool -change /usr/local/opt/qt/lib/QtSvg.framework/Versions/4/QtSvg @rpath/Deps/QtSvg ./PyQt4/QtDeclarative.so
install_name_tool -change /usr/local/opt/qt/lib/QtGui.framework/Versions/4/QtGui @rpath/Deps/QtGui ./PyQt4/QtDeclarative.so
install_name_tool -change /usr/local/opt/qt/lib/QtSql.framework/Versions/4/QtSql @rpath/Deps/QtSql ./PyQt4/QtDeclarative.so
install_name_tool -change /usr/local/opt/qt/lib/QtXmlPatterns.framework/Versions/4/QtXmlPatterns @rpath/Deps/QtXmlPatterns ./PyQt4/QtDeclarative.so
install_name_tool -change /usr/local/opt/qt/lib/QtNetwork.framework/Versions/4/QtNetwork @rpath/Deps/QtNetwork ./PyQt4/QtDeclarative.so
install_name_tool -change /usr/lib/libc++.1.dylib @rpath/Deps/libc++.1.dylib ./PyQt4/QtDeclarative.so
install_name_tool -change /usr/lib/libSystem.B.dylib @rpath/Deps/libSystem.B.dylib ./PyQt4/QtDeclarative.so
install_name_tool -change /usr/local/opt/qt/lib/QtDesigner.framework/Versions/4/QtDesigner @rpath/Deps/QtDesigner ./PyQt4/QtDesigner.so
install_name_tool -change /usr/local/opt/qt/lib/QtScript.framework/Versions/4/QtScript @rpath/Deps/QtScript ./PyQt4/QtDesigner.so
install_name_tool -change /usr/local/opt/qt/lib/QtCore.framework/Versions/4/QtCore @rpath/Deps/QtCore ./PyQt4/QtDesigner.so
install_name_tool -change /usr/local/opt/qt/lib/QtXml.framework/Versions/4/QtXml @rpath/Deps/QtXml ./PyQt4/QtDesigner.so
install_name_tool -change /usr/local/opt/qt/lib/QtGui.framework/Versions/4/QtGui @rpath/Deps/QtGui ./PyQt4/QtDesigner.so
install_name_tool -change /usr/lib/libc++.1.dylib @rpath/Deps/libc++.1.dylib ./PyQt4/QtDesigner.so
install_name_tool -change /usr/lib/libSystem.B.dylib @rpath/Deps/libSystem.B.dylib ./PyQt4/QtDesigner.so
install_name_tool -change /usr/local/opt/qt/lib/QtGui.framework/Versions/4/QtGui @rpath/Deps/QtGui ./PyQt4/QtGui.so
install_name_tool -change /usr/local/opt/qt/lib/QtCore.framework/Versions/4/QtCore @rpath/Deps/QtCore ./PyQt4/QtGui.so
install_name_tool -change /usr/lib/libc++.1.dylib @rpath/Deps/libc++.1.dylib ./PyQt4/QtGui.so
install_name_tool -change /usr/lib/libSystem.B.dylib @rpath/Deps/libSystem.B.dylib ./PyQt4/QtGui.so
install_name_tool -change /usr/local/opt/qt/lib/QtHelp.framework/Versions/4/QtHelp @rpath/Deps/QtHelp ./PyQt4/QtHelp.so
install_name_tool -change /usr/local/opt/qt/lib/QtSql.framework/Versions/4/QtSql @rpath/Deps/QtSql ./PyQt4/QtHelp.so
install_name_tool -change /usr/local/opt/qt/lib/QtCore.framework/Versions/4/QtCore @rpath/Deps/QtCore ./PyQt4/QtHelp.so
install_name_tool -change /usr/local/opt/qt/lib/QtGui.framework/Versions/4/QtGui @rpath/Deps/QtGui ./PyQt4/QtHelp.so
install_name_tool -change /usr/local/opt/qt/lib/QtNetwork.framework/Versions/4/QtNetwork @rpath/Deps/QtNetwork ./PyQt4/QtHelp.so
install_name_tool -change /usr/lib/libc++.1.dylib @rpath/Deps/libc++.1.dylib ./PyQt4/QtHelp.so
install_name_tool -change /usr/lib/libSystem.B.dylib @rpath/Deps/libSystem.B.dylib ./PyQt4/QtHelp.so
install_name_tool -change /usr/local/opt/qt/lib/QtMultimedia.framework/Versions/4/QtMultimedia @rpath/Deps/QtMultimedia ./PyQt4/QtMultimedia.so
install_name_tool -change /usr/local/opt/qt/lib/QtGui.framework/Versions/4/QtGui @rpath/Deps/QtGui ./PyQt4/QtMultimedia.so
install_name_tool -change /usr/local/opt/qt/lib/QtCore.framework/Versions/4/QtCore @rpath/Deps/QtCore ./PyQt4/QtMultimedia.so
install_name_tool -change /usr/lib/libc++.1.dylib @rpath/Deps/libc++.1.dylib ./PyQt4/QtMultimedia.so
install_name_tool -change /usr/lib/libSystem.B.dylib @rpath/Deps/libSystem.B.dylib ./PyQt4/QtMultimedia.so
install_name_tool -change /usr/local/opt/qt/lib/QtNetwork.framework/Versions/4/QtNetwork @rpath/Deps/QtNetwork ./PyQt4/QtNetwork.so
install_name_tool -change /usr/local/opt/qt/lib/QtCore.framework/Versions/4/QtCore @rpath/Deps/QtCore ./PyQt4/QtNetwork.so
install_name_tool -change /usr/lib/libc++.1.dylib @rpath/Deps/libc++.1.dylib ./PyQt4/QtNetwork.so
install_name_tool -change /usr/lib/libSystem.B.dylib @rpath/Deps/libSystem.B.dylib ./PyQt4/QtNetwork.so
install_name_tool -change /usr/local/opt/qt/lib/QtOpenGL.framework/Versions/4/QtOpenGL @rpath/Deps/QtOpenGL ./PyQt4/QtOpenGL.so
install_name_tool -change /usr/local/opt/qt/lib/QtGui.framework/Versions/4/QtGui @rpath/Deps/QtGui ./PyQt4/QtOpenGL.so
install_name_tool -change /usr/local/opt/qt/lib/QtCore.framework/Versions/4/QtCore @rpath/Deps/QtCore ./PyQt4/QtOpenGL.so
install_name_tool -change /usr/lib/libc++.1.dylib @rpath/Deps/libc++.1.dylib ./PyQt4/QtOpenGL.so
install_name_tool -change /usr/lib/libSystem.B.dylib @rpath/Deps/libSystem.B.dylib ./PyQt4/QtOpenGL.so
install_name_tool -change /usr/local/opt/qt/lib/QtScript.framework/Versions/4/QtScript @rpath/Deps/QtScript ./PyQt4/QtScript.so
install_name_tool -change /usr/local/opt/qt/lib/QtCore.framework/Versions/4/QtCore @rpath/Deps/QtCore ./PyQt4/QtScript.so
install_name_tool -change /usr/lib/libc++.1.dylib @rpath/Deps/libc++.1.dylib ./PyQt4/QtScript.so
install_name_tool -change /usr/lib/libSystem.B.dylib @rpath/Deps/libSystem.B.dylib ./PyQt4/QtScript.so
install_name_tool -change /usr/local/opt/qt/lib/QtScriptTools.framework/Versions/4/QtScriptTools @rpath/Deps/QtScriptTools ./PyQt4/QtScriptTools.so
install_name_tool -change /usr/local/opt/qt/lib/QtScript.framework/Versions/4/QtScript @rpath/Deps/QtScript ./PyQt4/QtScriptTools.so
install_name_tool -change /usr/local/opt/qt/lib/QtCore.framework/Versions/4/QtCore @rpath/Deps/QtCore ./PyQt4/QtScriptTools.so
install_name_tool -change /usr/local/opt/qt/lib/QtGui.framework/Versions/4/QtGui @rpath/Deps/QtGui ./PyQt4/QtScriptTools.so
install_name_tool -change /usr/lib/libc++.1.dylib @rpath/Deps/libc++.1.dylib ./PyQt4/QtScriptTools.so
install_name_tool -change /usr/lib/libSystem.B.dylib @rpath/Deps/libSystem.B.dylib ./PyQt4/QtScriptTools.so
install_name_tool -change /usr/local/opt/qt/lib/QtSql.framework/Versions/4/QtSql @rpath/Deps/QtSql ./PyQt4/QtSql.so
install_name_tool -change /usr/local/opt/qt/lib/QtCore.framework/Versions/4/QtCore @rpath/Deps/QtCore ./PyQt4/QtSql.so
install_name_tool -change /usr/local/opt/qt/lib/QtGui.framework/Versions/4/QtGui @rpath/Deps/QtGui ./PyQt4/QtSql.so
install_name_tool -change /usr/lib/libc++.1.dylib @rpath/Deps/libc++.1.dylib ./PyQt4/QtSql.so
install_name_tool -change /usr/lib/libSystem.B.dylib @rpath/Deps/libSystem.B.dylib ./PyQt4/QtSql.so
install_name_tool -change /usr/local/opt/qt/lib/QtSvg.framework/Versions/4/QtSvg @rpath/Deps/QtSvg ./PyQt4/QtSvg.so
install_name_tool -change /usr/local/opt/qt/lib/QtGui.framework/Versions/4/QtGui @rpath/Deps/QtGui ./PyQt4/QtSvg.so
install_name_tool -change /usr/local/opt/qt/lib/QtCore.framework/Versions/4/QtCore @rpath/Deps/QtCore ./PyQt4/QtSvg.so
install_name_tool -change /usr/lib/libc++.1.dylib @rpath/Deps/libc++.1.dylib ./PyQt4/QtSvg.so
install_name_tool -change /usr/lib/libSystem.B.dylib @rpath/Deps/libSystem.B.dylib ./PyQt4/QtSvg.so
install_name_tool -change /usr/local/opt/qt/lib/QtTest.framework/Versions/4/QtTest @rpath/Deps/QtTest ./PyQt4/QtTest.so
install_name_tool -change /usr/local/opt/qt/lib/QtCore.framework/Versions/4/QtCore @rpath/Deps/QtCore ./PyQt4/QtTest.so
install_name_tool -change /usr/local/opt/qt/lib/QtGui.framework/Versions/4/QtGui @rpath/Deps/QtGui ./PyQt4/QtTest.so
install_name_tool -change /usr/lib/libc++.1.dylib @rpath/Deps/libc++.1.dylib ./PyQt4/QtTest.so
install_name_tool -change /usr/lib/libSystem.B.dylib @rpath/Deps/libSystem.B.dylib ./PyQt4/QtTest.so
install_name_tool -change /usr/local/opt/qt/lib/QtWebKit.framework/Versions/4/QtWebKit @rpath/Deps/QtWebKit ./PyQt4/QtWebKit.so
install_name_tool -change /usr/local/opt/qt/lib/QtGui.framework/Versions/4/QtGui @rpath/Deps/QtGui ./PyQt4/QtWebKit.so
install_name_tool -change /usr/local/opt/qt/lib/QtCore.framework/Versions/4/QtCore @rpath/Deps/QtCore ./PyQt4/QtWebKit.so
install_name_tool -change /usr/local/opt/qt/lib/QtNetwork.framework/Versions/4/QtNetwork @rpath/Deps/QtNetwork ./PyQt4/QtWebKit.so
install_name_tool -change /usr/lib/libc++.1.dylib @rpath/Deps/libc++.1.dylib ./PyQt4/QtWebKit.so
install_name_tool -change /usr/lib/libSystem.B.dylib @rpath/Deps/libSystem.B.dylib ./PyQt4/QtWebKit.so
install_name_tool -change /usr/local/opt/qt/lib/QtXml.framework/Versions/4/QtXml @rpath/Deps/QtXml ./PyQt4/QtXml.so
install_name_tool -change /usr/local/opt/qt/lib/QtCore.framework/Versions/4/QtCore @rpath/Deps/QtCore ./PyQt4/QtXml.so
install_name_tool -change /usr/lib/libc++.1.dylib @rpath/Deps/libc++.1.dylib ./PyQt4/QtXml.so
install_name_tool -change /usr/lib/libSystem.B.dylib @rpath/Deps/libSystem.B.dylib ./PyQt4/QtXml.so
install_name_tool -change /usr/local/opt/qt/lib/QtXmlPatterns.framework/Versions/4/QtXmlPatterns @rpath/Deps/QtXmlPatterns ./PyQt4/QtXmlPatterns.so
install_name_tool -change /usr/local/opt/qt/lib/QtNetwork.framework/Versions/4/QtNetwork @rpath/Deps/QtNetwork ./PyQt4/QtXmlPatterns.so
install_name_tool -change /usr/local/opt/qt/lib/QtCore.framework/Versions/4/QtCore @rpath/Deps/QtCore ./PyQt4/QtXmlPatterns.so
install_name_tool -change /usr/lib/libc++.1.dylib @rpath/Deps/libc++.1.dylib ./PyQt4/QtXmlPatterns.so
install_name_tool -change /usr/lib/libSystem.B.dylib @rpath/Deps/libSystem.B.dylib ./PyQt4/QtXmlPatterns.so
